name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to Windows Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            powershell -Command "
              Write-Host '💻 Connecting to server...';
              cd 'C:\websites\brew-guide';

              Write-Host '📂 Current location:';
              Get-Location;

              Write-Host '👤 Current user:';
              $env:USERNAME;

              Write-Output '✅ Deploy triggered via GitHub Actions at ' (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | Out-File -FilePath 'C:\websites\brew-guide\deploy-log.txt' -Append;

              Write-Host '🔒 Marking directory as safe...';
              git config --global --add safe.directory 'C:/websites/brew-guide';

              Write-Host '🔍 Git status before pull:';
              git status | Out-File -FilePath 'C:\websites\brew-guide\git-status-before.txt';

              Write-Host '🔍 Git remote info:';
              git remote -v | Out-File -FilePath 'C:\websites\brew-guide\git-remote.txt';

              Write-Host '📦 Pulling latest code...';
              git pull origin main | Tee-Object -FilePath 'C:\websites\brew-guide\git-pull-log.txt' -Append;

              Write-Host '🛑 Stopping app via PM2...';
              $env:PM2_HOME = 'C:\pm2'
              pm2 stop brew-guide;

              Write-Host '📦 Installing dependencies...';
              npm install | Tee-Object -FilePath 'C:\websites\brew-guide\npm-install-log.txt' -Append;

              Write-Host '🔨 Building project...';
              npm run build | Tee-Object -FilePath 'C:\websites\brew-guide\npm-build-log.txt' -Append;

              Write-Host '🚀 Restarting app...';
              pm2 restart brew-guide;

              Write-Host '✅ Deploy completed at ' (Get-Date -Format 'yyyy-MM-dd HH:mm:ss');
            "
