name: Deploy to Windows Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          cd C:\websites\brew-guide
          "C:\Program Files\Git\cmd\git.exe" pull origin main
          pm2 stop brew-guide
          "C:\Program Files\nodejs\npm.cmd" install
          "C:\Program Files\nodejs\npm.cmd" run build
          pm2 restart brew-guide
          echo "Deploy completed at $(Get-Date)"
