name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Windows Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and Build via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd C:/websites/brew-guide

            echo "🔄 Pulling latest code..."
            git pull origin main

            echo "📦 Installing dependencies..."
            npm install

            echo "🏗️ Building project..."
            npm run build

            echo "🧹 Removing old pm2 process (if exists)..."
            pm2 delete brew-guide || echo "No old process"

            echo "🚀 Starting new serve process..."
            pm2 serve out 3000 --name brew-guide
