name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build on Server
    runs-on: ubuntu-latest
    steps:
      - name: Execute build via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/brew-guide  # 替换为你的服务器项目路径
            export http_proxy=http://127.0.0.1:47890                                                                   
            export https_proxy=http://127.0.0.1:47890
            export PATH=$PATH:~/node-v20.9.0-linux-x64/bin/
            git pull origin main   # 如果需要同步最新代码
            pnpm install
            pnpm run build
